### ISSUE TITLE
Request: Quiescent draw measurement

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/SparkFun_Buck_Regulator_AP63357DV-7#1]
@SFE-Brudnerd can you measure the quiescent draw of this board without a load?

Looking at the schematic, I'm worried about the voltage divider on VEN. Can you clarify again its purpose?

Cheers,
Adam

**Comment by SFE-Brudnerd** [comment]
Hey @adamgarbo I can certainly do that measurement. 

The purpose is to raise the voltage for the UVLO of the device. I'll paraphrase from this lovely app note from TI, it's useful for battery operated devices in order to have more predictable and robust performance. 

This is characterized by the following:
- Avoids damaging a battery by draining it too far if the battery minimum voltage is above the default UVLO voltage
- Partially turning ON/OFF transistors
- Bandgap reference may produce the wrong voltage (I don't believe this is an issue with this specific device, but can still be an issue)
- Logic/control signals may end up with the wrong voltage

![image](https://user-images.githubusercontent.com/101155592/218512959-400916ee-6839-4bf9-85ee-8bd9dc81109f.png)

In the above figure, TI points out that while the device may operate in the yellow 'functional' regions, it may not deliver the full performance. There's a good bit of easily digestible detail in the app note, so I've linked it below.

https://www.ti.com/lit/an/slva769a/slva769a.pdf

**Comment by SFE-Brudnerd** [comment]
Hey @adamgarbo, here are the results for the two BabyBucks I had laying around. My recommendation to you would again be to remove the resistors modifying the UVLO if you require a lower quiescent current. Hope this was helpful.

| Input Voltage (V) | Dev 1 Iq (uA) | Dev 2 Iq (uA) | Average (uA) |
| - | - | - | - |
| 6 | 194 | 198 | 196 |
| 12 | 198 | 220 | 209 |
| 24 | 281 | 300 | 290.5 |
| 32 | 347 | 363 | 355 |

**Comment by adamgarbo** [comment]
Thanks @SFE-Brudnerd!

Did you happen to measure Iq when EN was disabled?

Cheers,
Adam

**Comment by SFE-Brudnerd** [comment]
I hadn't, however it was easy enough to set it back up.

| Input Voltage (V) | Dev 1 (uA) |
| - | - |
| 6 | 65 |
| 12 | 129 |
| 24 | 260 |
| 32 | 330 |
